### ISSUE TITLE
Do not create (or clean-up) the directory structure/Portfile if something fails

### ISSUE THREAD

**Issue by reneeotten** [macports/upt-macports#42]
When testing the templates, I ran into a few situations where while creating the package we would stumble upon an ```upt.upt.ArchiveUnavailable: No such archive could be found``` problem.

For example, 
```
py-scitools
[INFO    ] [Backend] Hello, creating the package
[INFO    ] [Backend] Creating the directory structure in /tmp/upt-pypi-packaging
[INFO    ] [Backend] Created /tmp/upt-pypi-packaging/python/py-scitools
[INFO    ] [Backend] Creating the Portfile
Traceback (most recent call last):
  File "/tmp/test-3.7/bin/upt", line 11, in <module>
    load_entry_point('upt==0.9', 'console_scripts', 'upt')()
  File "/tmp/test-3.7/lib/python3.7/site-packages/upt/upt.py", line 302, in main
    backend.create_package(upt_pkg, output=args.output)
  File "/tmp/test-3.7/lib/python3.7/site-packages/upt_macports-0.1-py3.7.egg/upt_macports/upt_macports.py", line 253, in create_package
  File "/tmp/test-3.7/lib/python3.7/site-packages/upt_macports-0.1-py3.7.egg/upt_macports/upt_macports.py", line 22, in create_package
  File "/tmp/test-3.7/lib/python3.7/site-packages/upt_macports-0.1-py3.7.egg/upt_macports/upt_macports.py", line 51, in _create_portfile
  File "/tmp/test-3.7/lib/python3.7/site-packages/upt_macports-0.1-py3.7.egg/upt_macports/upt_macports.py", line 64, in _render_makefile_template
  File "/tmp/test-3.7/lib/python3.7/site-packages/Jinja2-2.10.1-py3.7.egg/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/tmp/test-3.7/lib/python3.7/site-packages/Jinja2-2.10.1-py3.7.egg/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/tmp/test-3.7/lib/python3.7/site-packages/Jinja2-2.10.1-py3.7.egg/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/tmp/test-3.7/lib/python3.7/site-packages/Jinja2-2.10.1-py3.7.egg/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "<template>", line 19, in top-level template code
  File "<template>", line 8, in block "nameversion"
  File "/tmp/test-3.7/lib/python3.7/site-packages/upt_macports-0.1-py3.7.egg/upt_macports/upt_macports.py", line 144, in _python_root_name
  File "/tmp/test-3.7/lib/python3.7/site-packages/upt/upt.py", line 187, in get_archive
    raise ArchiveUnavailable()
upt.upt.ArchiveUnavailable: No such archive could be found
```

afterwards we do end up with an empty Portfile in the ```/python/py-scitools`` directory. One way around this would perhaps to first attempt to generate a Portfile in a temporary directory and only copy this over once everything finishes correctly. Or, alternatively, once we run into such Exceptions we could do some clean-up.

**Comment by Korusuke** [comment]
I tried to package `scitools` and got the following error which doesn't generate the blank Portfiles:
```
Traceback (most recent call last):
  File "/usr/local/bin/upt", line 11, in <module>
    load_entry_point('upt==0.9', 'console_scripts', 'upt')()
  File "/usr/local/lib/python3.6/dist-packages/upt-0.9-py3.6.egg/upt/upt.py", line 318, in main
  File "/usr/local/lib/python3.6/dist-packages/upt-0.9-py3.6.egg/upt/upt.py", line 328, in package
  File "/home/kiteretsu/.local/lib/python3.6/site-packages/upt_pypi/upt_pypi.py", line 381, in parse
    'archives': self.get_archives(self.json['releases'][version]),
  File "/home/kiteretsu/.local/lib/python3.6/site-packages/upt_pypi/upt_pypi.py", line 362, in get_archives
    url, size, md5, sha256 = self.get_archive_info(release, 'sdist')
  File "/home/kiteretsu/.local/lib/python3.6/site-packages/upt_pypi/upt_pypi.py", line 30, in get_archive_info
    raise ValueError(f'No archive of type "{kind}" could be found')
ValueError: No archive of type "sdist" could be found
```

but when I tried uninstalling and installing upt and upt-pypi then I ended up with the same error as yours.
We can sure handle the error here but I guess if archive is not available it should fail at frontend as archive is an important thing.

**Comment by reneeotten** [comment]
> We can sure handle the error here but I guess if archive is not available it should fail at frontend as archive is an important thing.

well, ```upt``` does raise an ```ArchiveUnavailable``` error so I think that's what is supposed to happen (@Steap ?). The issue is though that it will currently only find that out when you call ```self._render_makefile_template()```.

If the "--output" option is selected what happens is:
```
self._create_output_directories(upt_pkg, output)
self._create_portfile()
````
, where the latter one is calling ```self._render_makefile_template()```.

In other words, you have already created the directories before finding out if ```upt``` can actual package it. And since we do not clean-up after this error, we are left with the directory structure and empty Portfile. Hence my two possible suggestions in the first message to get around this. I think I prefer to first try generate the Portfile in a temporary directory and once this finishes correctly copy it to its final destination. But before you start coding something let's see what @Steap thinks (perhaps some of this could/should go in ```upt```).

**Comment by Steap** [comment]
Scitools has not uploaded any file (no tar.gz, no wheel), so get_archive cannot find anything. The get_archive method may raise an exception, and upt-macports should handle it.
