### ISSUE TITLE
Can't create a template for `pyzbar`

### ISSUE THREAD

**Issue by catap** [macports/upt-macports#70]
Installed:
```
  py39-upt-cpan @0.6.1_0 (active)
  py39-upt-macports @0.1-20200607_0 (active)
  py39-upt-pypi @0.6_0 (active)
  py39-upt-rubygems @0.4.1_0 (active)
```
when run `upt package -f pypi -b macports -o . -r pyzbar` it crashed:
```
[INFO    ] [Backend] Creating MacPorts package for pyzbar
[INFO    ] [Backend] Found license MIT
[ERROR   ] [Backend] Could not determine the type of the source archive
Traceback (most recent call last):
  File "/opt/local/bin/upt", line 33, in <module>
    sys.exit(load_entry_point('upt==0.12', 'console_scripts', 'upt')())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/upt/upt.py", line 497, in main
    package(name, version, frontend, backend, args.output,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/upt/upt.py", line 382, in package
    backend.create_package(upt_pkg, output=output)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/upt_macports/upt_macports.py", line 258, in create_package
    packager.create_package(upt_pkg, output)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/upt_macports/upt_macports.py", line 20, in create_package
    portfile_content = self._render_makefile_template()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/upt_macports/upt_macports.py", line 57, in _render_makefile_template
    return template.render(pkg=self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/upt_macports/templates/python.Portfile", line 1, in top-level template code
    {% extends 'base.Portfile' %}
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/upt_macports/templates/base.Portfile", line 41, in top-level template code
    checksums           rmd160  {{ pkg.upt_pkg.archives[0].rmd160 }} \
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: list object has no element 0
```

**Comment by Steap** [comment]
#71 should fix your issue. The root cause is that no tar.gz has been uploaded to PyPI. I'd suggest contacting the maintainer to ask them to upload tarballs from now on, but the project does not seem very active :-(

**Comment by catap** [comment]
@Steap yep, and I've used another PortGroup to create this port: https://github.com/macports/macports-ports/pull/12197
